### ISSUE TITLE
Differing behavior from local FITS on empty files

### ISSUE THREAD

**Issue by bnbalsamo** [harvard-lts/FITSservlet#21]
When posting local file data to the servlet examine endpoint, in the instance where the file is empty (0 bytes) the server returns a status code of 400 and the error message " Missing File Data. "

Locally installed FITS processes empty files with no issues. Producing a record with minimal information, but a valid FITS output file.

Example output demonstrating this below:

```
# Create an empty file
$ touch emptyfile.txt
# It's really empty
$ du emptyfile.txt 
0	emptyfile.txt
# Post the file to the examine endpoint - This returns an error
$ curl -k -F datafile=@emptyfile.txt http://127.0.0.1:8080/fits/examine
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error><statusCode>400</statusCode><message> Missing File Data. </message><request>http://127.0.0.1:8080/fits/examine</request></error>
# Run FITS locally - This returns a record
$ fits -i emptyfile.txt
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.8.6" timestamp="8/11/16 11:16 AM">
    [... valid record XML ...]
</fits>
```

**Proposed Solutions**

- In my own opinion it would be ideal to receive a record from the web interface for any file that FITS would run on locally (with the obvious caveats that some information may be modified or inaccessible owing to the nature of transferring the file). Returning a record for an empty file when the endpoint receives a post of a blank file.

- If that isn't possible for technical/pragmatic reasons I'd recommend including a note about this behavior (and any other differences from a local FITS installation) in the documentation in an easily accessible place. Differences I have noticed thus far:

    - This case (behavior on empty files)
    - Reported filenames of uploaded files
    - Reported paths of uploaded files (this also exposes the server file system to a degree)
    - File modified times (it appears as though a copy of the file is instantiated on the server at time of analysis)

**Comment by daveneiman** [comment]
Hello,

The upcoming release of this project will allow a 0-length file as valid input, the same as stand-alone FITS. The filename as returned in the FITS XML will be the real file name, instead of the temporary generated filename.

Unfortunately a copy of the file is generated by the servlet before being sent to FITS which will affect its timestamp. Also, it's one of the tools embedded within FITS that generates the absolute file path in the generated XML which will expose the server file system. If this is a serious problem then this tool (OIS File Information) can be removed from the fits.xml configuration file.
